services:
  mc:
    image: itzg/minecraft-server
    env_file:
      - .env
    ports:
      - "25565:25565"
    volumes:
      - ./mc-data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      restore-backup:
        condition: service_completed_successfully
  restore-backup:
    image: itzg/mc-backup
    user: "1000"
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      # Must be same mount as mc service, needs to be writable
      - ./mc-data:/data
      # Must be same mount as backups service, but can be read-only
      - ./mc-backups:/backups:ro
  backups:
    image: itzg/mc-backup
    user: "1000"
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
    volumes:
      - ./mc-data:/data:ro
      - ./mc-backups:/backups