services:
  mc:
    image: itzg/minecraft-server
    environment:
      SERVER_NAME: "UFAZ"
      MOTD: "Welcome to §9UFAZ §n§fMinecraft §cServer"
      SEED: ""
      ICON: ""
      WHITELIST_FILE: "mc-whitelist.json"
      OPS: |
        Admin
      OVERRIDE_ICON: "false" # change later
      EULA: "true"
      MEMORY: "4G" # change later
      LOG_TIMESTAMP: "true"
      TYPE: "FABRIC"
      VERSION: "1.20.6"
      DIFFICULTY: "hard"
      MAX_PLAYERS: "200"
      MAX_WORLD_SIZE: "50000"
      MAX_BUILD_HEIGHT: "320"
      ONLINE_MODE: "false"
      STOP_SERVER_ANNOUNCE_DELAY: "300"
      ENABLE_WHITELIST: "true"
      ENABLE_AUTOPAUSE: "true"
      AUTOPAUSE_TIMEOUT_EST: "1800"
      MAX_TICK_TIME: "120"
      EXISTING_WHITELIST_FILE: SYNC_FILE_MERGE_LIST
    ports:
      - "25565:25565"
    volumes:
      - ./mc-data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
    depends_on:
      restore-backup:
        condition: service_completed_successfully
  restore-backup:
    image: itzg/mc-backup
    user: "1000"
    restart: no
    entrypoint: restore-tar-backup
    volumes:
      # Must be same mount as mc service, needs to be writable
      - ./mc-data:/data
      # Must be same mount as backups service, but can be read-only
      - ./mc-backups:/backups:ro
  backups:
    image: itzg/mc-backup
    user: "1000"
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "12h"
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
    volumes:
      - ./mc-data:/data:ro
      - ./mc-backups:/backups